#!/bin/bash

if [ $# -ne 2 ]; then
    echo ""
    echo "Script usage: "
    echo "   makeWebpage <input.md> <output.html>"
    echo ""
    exit 1
fi

# HTML
pandoc -N -s ${PANDOC_TEMPLATES}/cross_references.yaml \
       ${1} -o ${2} --highlight-style tango --mathjax --css ${PANDOC_TEMPLATES}/webstyle_template.css --toc\
       --filter ${PANDOC_FILTERS}/pandoc-crossref\
       --filter pandoc-citeproc
