#!/bin/bash

if [ $# -ne 2 ]; then
    echo ""
    echo "Script usage: "
    echo "   makeSlides <input.md> <output.pdf>"
    echo ""
    exit 1
    fi

# Beamer slides
pandoc -N -s ${PANDOC_TEMPLATES}/cross_references.yaml ${1} -o ${2}\
       --filter ${PANDOC_FILTERS}/pandoc-crossref\
       --filter pandoc-citeproc\
       --to beamer --template ${PANDOC_TEMPLATES}/slides_template.tex --slide-level=2 \
       --highlight-style tango\
       -V theme="CambridgeUS" -V colortheme="seagull" -V fonttheme="structurebold"\
       -V colorlinks\
       -V toc\
       -V fontsize="10pt"\
       -V fontfamily="libertine"

 
